export interface Actor {
  value: string;
  label: string;
  industry: string;
  scene: string;
}

const raw: [string, string, string, string][] = [
  // Restaurant & Cafe - Kitchen
  ["restaurant+&+cafe-kitchen-woman+bandana+chef", "Woman Bandana Chef", "Restaurant & Cafe", "Kitchen"],
  ["restaurant+&+cafe-kitchen-woman+blonde+headband", "Woman Blonde Headband", "Restaurant & Cafe", "Kitchen"],
  ["restaurant+&+cafe-kitchen-woman+brunette+bandana", "Woman Brunette Bandana", "Restaurant & Cafe", "Kitchen"],
  ["restaurant+&+cafe-kitchen-woman+cap+barista", "Woman Cap Barista", "Restaurant & Cafe", "Kitchen"],
  ["restaurant+&+cafe-kitchen-man+blonde+chef", "Man Blonde Chef", "Restaurant & Cafe", "Kitchen"],
  ["restaurant+&+cafe-kitchen-man+wavy+barista", "Man Wavy Barista", "Restaurant & Cafe", "Kitchen"],
  ["restaurant+&+cafe-kitchen-man+asian+chef", "Man Asian Chef", "Restaurant & Cafe", "Kitchen"],
  ["restaurant+&+cafe-kitchen-man+cornrows+barista", "Man Cornrows Barista", "Restaurant & Cafe", "Kitchen"],
  // Restaurant & Cafe - Cafe
  ["restaurant+&+cafe-cafe-woman+blonde+glasses", "Woman Blonde Glasses", "Restaurant & Cafe", "Cafe"],
  ["restaurant+&+cafe-cafe-woman+black+afro", "Woman Black Afro", "Restaurant & Cafe", "Cafe"],
  ["restaurant+&+cafe-cafe-woman+redhead+wavy", "Woman Redhead Wavy", "Restaurant & Cafe", "Cafe"],
  ["restaurant+&+cafe-cafe-woman+brunette+updo", "Woman Brunette Updo", "Restaurant & Cafe", "Cafe"],
  ["restaurant+&+cafe-cafe-woman+black+wavy", "Woman Black Wavy", "Restaurant & Cafe", "Cafe"],
  ["restaurant+&+cafe-cafe-man+blonde+slickedback", "Man Blonde Slickedback", "Restaurant & Cafe", "Cafe"],
  ["restaurant+&+cafe-cafe-man+wavy+brown", "Man Wavy Brown", "Restaurant & Cafe", "Cafe"],
  ["restaurant+&+cafe-cafe-man+platinum+sunglasses", "Man Platinum Sunglasses", "Restaurant & Cafe", "Cafe"],
  ["restaurant+&+cafe-cafe-man+asian+dark", "Man Asian Dark", "Restaurant & Cafe", "Cafe"],
  ["restaurant+&+cafe-cafe-man+cornrows+tattoo", "Man Cornrows Tattoo", "Restaurant & Cafe", "Cafe"],
  ["restaurant+&+cafe-cafe-man+asian+green", "Man Asian Green", "Restaurant & Cafe", "Cafe"],
  // Health & Sports - Studio
  ["health+&+sports-studio-man+tattoo+buzzcut+flexing", "Man Tattoo Buzzcut Flexing", "Health & Sports", "Studio"],
  ["health+&+sports-studio-man+black+muscular", "Man Black Muscular", "Health & Sports", "Studio"],
  ["health+&+sports-studio-woman+brunette+wavy+headband", "Woman Brunette Wavy Headband", "Health & Sports", "Studio"],
  ["health+&+sports-studio-man+asian+jacket", "Man Asian Jacket", "Health & Sports", "Studio"],
  ["health+&+sports-studio-woman+ginger+freckles", "Woman Ginger Freckles", "Health & Sports", "Studio"],
  ["health+&+sports-studio-man+curly+muscular+bench", "Man Curly Muscular Bench", "Health & Sports", "Studio"],
  ["health+&+sports-studio-man+platinum+shaker+table", "Man Platinum Shaker Table", "Health & Sports", "Studio"],
  ["health+&+sports-studio-man+platinum+jacket", "Man Platinum Jacket", "Health & Sports", "Studio"],
  ["health+&+sports-studio-woman+platinum+curly", "Woman Platinum Curly", "Health & Sports", "Studio"],
  ["health+&+sports-studio-woman+blonde+ponytail", "Woman Blonde Ponytail", "Health & Sports", "Studio"],
  // Health & Sports - Outdoor
  ["health+&+sports-outdoor-woman+brunette+wavy+airport", "Woman Brunette Wavy Airport", "Health & Sports", "Outdoor"],
  ["health+&+sports-outdoor-man+mature+hiking+mountain", "Man Mature Hiking Mountain", "Health & Sports", "Outdoor"],
  ["health+&+sports-outdoor-man+platinum+garden", "Man Platinum Garden", "Health & Sports", "Outdoor"],
  ["health+&+sports-outdoor-man+asian+meadow", "Man Asian Meadow", "Health & Sports", "Outdoor"],
  ["health+&+sports-outdoor-man+asian+basketball", "Man Asian Basketball", "Health & Sports", "Outdoor"],
  ["health+&+sports-outdoor-man+mature+lounge", "Man Mature Lounge", "Health & Sports", "Outdoor"],
  ["health+&+sports-outdoor-man+braids+hiking", "Man Braids Hiking", "Health & Sports", "Outdoor"],
  ["health+&+sports-outdoor-woman+brunette+ponytail+park", "Woman Brunette Ponytail Park", "Health & Sports", "Outdoor"],
  ["health+&+sports-outdoor-woman+brunette+meadow", "Woman Brunette Meadow", "Health & Sports", "Outdoor"],
  ["health+&+sports-outdoor-woman+redbraids+basketball", "Woman Redbraids Basketball", "Health & Sports", "Outdoor"],
  ["health+&+sports-outdoor-woman+afro+park", "Woman Afro Park", "Health & Sports", "Outdoor"],
  ["health+&+sports-outdoor-woman+redhead+straight+airport", "Woman Redhead Straight Airport", "Health & Sports", "Outdoor"],
  ["health+&+sports-outdoor-woman+redbraids+hiking", "Woman Redbraids Hiking", "Health & Sports", "Outdoor"],
  ["health+&+sports-outdoor-woman+blonde+headband+meadow", "Woman Blonde Headband Meadow", "Health & Sports", "Outdoor"],
  ["health+&+sports-outdoor-woman+brunette+cap+track", "Woman Brunette Cap Track", "Health & Sports", "Outdoor"],
  ["health+&+sports-outdoor-man+platinum+basketball", "Man Platinum Basketball", "Health & Sports", "Outdoor"],
  // Health & Sports - Kitchen
  ["health+&+sports-kitchen-woman+dark+wavy", "Woman Dark Wavy", "Health & Sports", "Kitchen"],
  ["health+&+sports-kitchen-woman+brunette+ponytail", "Woman Brunette Ponytail", "Health & Sports", "Kitchen"],
  ["health+&+sports-kitchen-woman+blonde+bun", "Woman Blonde Bun", "Health & Sports", "Kitchen"],
  ["health+&+sports-kitchen-man+asian+cap", "Man Asian Cap", "Health & Sports", "Kitchen"],
  ["health+&+sports-kitchen-man+dark+tiedye", "Man Dark Tiedye", "Health & Sports", "Kitchen"],
  ["health+&+sports-kitchen-man+dark+fridge", "Man Dark Fridge", "Health & Sports", "Kitchen"],
  ["health+&+sports-kitchen-man+dark+tanktop", "Man Dark Tanktop", "Health & Sports", "Kitchen"],
  ["health+&+sports-kitchen-woman+blonde+fridge", "Woman Blonde Fridge", "Health & Sports", "Kitchen"],
  ["health+&+sports-kitchen-woman+blonde+fridgepov", "Woman Blonde Fridgepov", "Health & Sports", "Kitchen"],
  ["health+&+sports-kitchen-man+cornrows+fridge", "Man Cornrows Fridge", "Health & Sports", "Kitchen"],
  ["health+&+sports-kitchen-man+braids+fridgepov", "Man Braids Fridgepov", "Health & Sports", "Kitchen"],
  // Health & Sports - Gym
  ["health+&+sports-gym-woman+curly+headband", "Woman Curly Headband", "Health & Sports", "Gym"],
  ["health+&+sports-gym-woman+redhead+braids", "Woman Redhead Braids", "Health & Sports", "Gym"],
  ["health+&+sports-gym-woman+curly+boxing", "Woman Curly Boxing", "Health & Sports", "Gym"],
  ["health+&+sports-gym-woman+platinum+boxing", "Woman Platinum Boxing", "Health & Sports", "Gym"],
  ["health+&+sports-gym-man+cornrows+tattoos", "Man Cornrows Tattoos", "Health & Sports", "Gym"],
  ["health+&+sports-gym-woman+platinum+sportsbra", "Woman Platinum Sportsbra", "Health & Sports", "Gym"],
  ["health+&+sports-gym-woman+blonde+green", "Woman Blonde Green", "Health & Sports", "Gym"],
  ["health+&+sports-gym-woman+blonde+locker", "Woman Blonde Locker", "Health & Sports", "Gym"],
  ["health+&+sports-gym-woman+dark+bun", "Woman Dark Bun", "Health & Sports", "Gym"],
  ["health+&+sports-gym-woman+brunette+freckles", "Woman Brunette Freckles", "Health & Sports", "Gym"],
  ["health+&+sports-gym-woman+dark+locker", "Woman Dark Locker", "Health & Sports", "Gym"],
  ["health+&+sports-gym-woman+redhead+freckles", "Woman Redhead Freckles", "Health & Sports", "Gym"],
  // Health & Sports - Car
  ["health+&+sports-car-woman+blonde+freckles", "Woman Blonde Freckles", "Health & Sports", "Car"],
  ["health+&+sports-car-woman+blonde+braid", "Woman Blonde Braid", "Health & Sports", "Car"],
  ["health+&+sports-car-man+dark+tanktop", "Man Dark Tanktop", "Health & Sports", "Car"],
  ["health+&+sports-car-man+braids+tattoos", "Man Braids Tattoos", "Health & Sports", "Car"],
  ["health+&+sports-car-woman+blonde+sunglasses", "Woman Blonde Sunglasses", "Health & Sports", "Car"],
  ["health+&+sports-car-man+twists+plaid", "Man Twists Plaid", "Health & Sports", "Car"],
  ["health+&+sports-car-woman+dark+hoodie", "Woman Dark Hoodie", "Health & Sports", "Car"],
  ["health+&+sports-car-man+dark+hoodie", "Man Dark Hoodie", "Health & Sports", "Car"],
  // Fashion - Studio
  ["fashion-studio-woman+dark+straight", "Woman Dark Straight", "Fashion", "Studio"],
  ["fashion-studio-woman+redhead+tanktop", "Woman Redhead Tanktop", "Fashion", "Studio"],
  ["fashion-studio-woman+blonde+bangs", "Woman Blonde Bangs", "Fashion", "Studio"],
  ["fashion-studio-man+curly+grey", "Man Curly Grey", "Fashion", "Studio"],
  ["fashion-studio-man+brown+silver", "Man Brown Silver", "Fashion", "Studio"],
  ["fashion-studio-woman+dark+grey", "Woman Dark Grey", "Fashion", "Studio"],
  ["fashion-studio-woman+blonde+black", "Woman Blonde Black", "Fashion", "Studio"],
  ["fashion-studio-woman+redhead+denim", "Woman Redhead Denim", "Fashion", "Studio"],
  // Fashion - Dressing Room
  ["fashion-dressingroom-woman+brunette+wavy", "Woman Brunette Wavy", "Fashion", "Dressing Room"],
  ["fashion-dressingroom-woman+redhead+freckles", "Woman Redhead Freckles", "Fashion", "Dressing Room"],
  ["fashion-dressingroom-woman+redhead+green", "Woman Redhead Green", "Fashion", "Dressing Room"],
  ["fashion-dressingroom-man+curly+dark", "Man Curly Dark", "Fashion", "Dressing Room"],
  ["fashion-dressingroom-woman+dark+short", "Woman Dark Short", "Fashion", "Dressing Room"],
  ["fashion-dressingroom-woman+blonde+black", "Woman Blonde Black", "Fashion", "Dressing Room"],
  // Fashion - Accessories
  ["fashion-accessories-woman+redhead+freckles", "Woman Redhead Freckles", "Fashion", "Accessories"],
  ["fashion-accessories-man+curly+brown", "Man Curly Brown", "Fashion", "Accessories"],
  ["fashion-accessories-man+brown+black", "Man Brown Black", "Fashion", "Accessories"],
  ["fashion-accessories-woman+dark+grey", "Woman Dark Grey", "Fashion", "Accessories"],
  // Electronic - Studio
  ["electronic-studio-man+curly+dark", "Man Curly Dark", "Electronic", "Studio"],
  ["electronic-studio-man+curly+white", "Man Curly White", "Electronic", "Studio"],
  ["electronic-studio-man+blonde+grey", "Man Blonde Grey", "Electronic", "Studio"],
  ["electronic-studio-woman+redhead+white", "Woman Redhead White", "Electronic", "Studio"],
  ["electronic-studio-woman+redhead+navy", "Woman Redhead Navy", "Electronic", "Studio"],
  ["electronic-studio-woman+blonde+turtleneck", "Woman Blonde Turtleneck", "Electronic", "Studio"],
  // Electronic - Outdoor
  ["electronic-outdoor-man+blonde+hoodie", "Man Blonde Hoodie", "Electronic", "Outdoor"],
  ["electronic-outdoor-man+buzzcut+sweater", "Man Buzzcut Sweater", "Electronic", "Outdoor"],
  ["electronic-outdoor-man+wavy+blue", "Man Wavy Blue", "Electronic", "Outdoor"],
  ["electronic-outdoor-woman+blonde+tank", "Woman Blonde Tank", "Electronic", "Outdoor"],
  ["electronic-outdoor-man+wavy+sweatshirt", "Man Wavy Sweatshirt", "Electronic", "Outdoor"],
  ["electronic-outdoor-man+brown+bomber", "Man Brown Bomber", "Electronic", "Outdoor"],
  ["electronic-outdoor-man+curly+grey", "Man Curly Grey", "Electronic", "Outdoor"],
  ["electronic-outdoor-woman+dark+bob", "Woman Dark Bob", "Electronic", "Outdoor"],
  ["electronic-outdoor-man+dark+casual", "Man Dark Casual", "Electronic", "Outdoor"],
  ["electronic-outdoor-man+curly+freckles", "Man Curly Freckles", "Electronic", "Outdoor"],
  // Electronic - Kitchen
  ["electronic-kitchen-man+blonde+beige", "Man Blonde Beige", "Electronic", "Kitchen"],
  ["electronic-kitchen-man+curly+cardigan", "Man Curly Cardigan", "Electronic", "Kitchen"],
  ["electronic-kitchen-man+curly+stubble", "Man Curly Stubble", "Electronic", "Kitchen"],
  ["electronic-kitchen-woman+redhead+freckles", "Woman Redhead Freckles", "Electronic", "Kitchen"],
  ["electronic-kitchen-woman+brunette+neon", "Woman Brunette Neon", "Electronic", "Kitchen"],
  // Electronic - Decorative
  ["electronic-decorative-woman+dark+blue", "Woman Dark Blue", "Electronic", "Decorative"],
  ["electronic-decorative-man+curly+vneck", "Man Curly Vneck", "Electronic", "Decorative"],
  ["electronic-decorative-man+curly+sunset", "Man Curly Sunset", "Electronic", "Decorative"],
  ["electronic-decorative-man+blonde+polo", "Man Blonde Polo", "Electronic", "Decorative"],
  ["electronic-decorative-man+wavy+tan", "Man Wavy Tan", "Electronic", "Decorative"],
  ["electronic-decorative-woman+redhead+dark", "Woman Redhead Dark", "Electronic", "Decorative"],
  ["electronic-decorative-woman+redhead+warm", "Woman Redhead Warm", "Electronic", "Decorative"],
  ["electronic-decorative-man+brown+slat", "Man Brown Slat", "Electronic", "Decorative"],
  ["electronic-decorative-man+brown+black", "Man Brown Black", "Electronic", "Decorative"],
  ["electronic-decorative-man+curly+olive", "Man Curly Olive", "Electronic", "Decorative"],
  ["electronic-decorative-man+mature+denim", "Man Mature Denim", "Electronic", "Decorative"],
  // Electronic - Gamer
  ["electronic-gamer-man+blonde+hoodie", "Man Blonde Hoodie", "Electronic", "Gamer"],
  ["electronic-gamer-man+blonde+knit", "Man Blonde Knit", "Electronic", "Gamer"],
  ["electronic-gamer-man+wavy+charcoal", "Man Wavy Charcoal", "Electronic", "Gamer"],
  ["electronic-gamer-man+wavy+olive", "Man Wavy Olive", "Electronic", "Gamer"],
  ["electronic-gamer-woman+redhead+black", "Woman Redhead Black", "Electronic", "Gamer"],
  ["electronic-gamer-woman+blonde+earrings", "Woman Blonde Earrings", "Electronic", "Gamer"],
  ["electronic-gamer-woman+dark+blue", "Woman Dark Blue", "Electronic", "Gamer"],
  // Electronic - Car
  ["electronic-car-woman+redhead+freckles", "Woman Redhead Freckles", "Electronic", "Car"],
  ["electronic-car-woman+brunette+bob", "Woman Brunette Bob", "Electronic", "Car"],
  ["electronic-car-man+curly+charcoal", "Man Curly Charcoal", "Electronic", "Car"],
  ["electronic-car-man+brown+black", "Man Brown Black", "Electronic", "Car"],
  ["electronic-car-man+dark+polo", "Man Dark Polo", "Electronic", "Car"],
  ["electronic-car-man+curly+grey", "Man Curly Grey", "Electronic", "Car"],
  ["electronic-car-man+blonde+blue", "Man Blonde Blue", "Electronic", "Car"],
  // Electronic - Bathroom
  ["electronic-bathroom-woman+redhead+teal", "Woman Redhead Teal", "Electronic", "Bathroom"],
  ["electronic-bathroom-woman+blonde+bangs", "Woman Blonde Bangs", "Electronic", "Bathroom"],
  ["electronic-bathroom-woman+dark+wavy", "Woman Dark Wavy", "Electronic", "Bathroom"],
  ["electronic-bathroom-man+curly+teal", "Man Curly Teal", "Electronic", "Bathroom"],
  ["electronic-bathroom-man+blonde+teal", "Man Blonde Teal", "Electronic", "Bathroom"],
  ["electronic-bathroom-man+wavy+black", "Man Wavy Black", "Electronic", "Bathroom"],
  ["electronic-bathroom-man+dark+brush", "Man Dark Brush", "Electronic", "Bathroom"],
  ["electronic-bathroom-man+brown+led", "Man Brown Led", "Electronic", "Bathroom"],
  ["electronic-bathroom-man+mature+navy", "Man Mature Navy", "Electronic", "Bathroom"],
  // Beauty - Studio
  ["beauty-studio-woman+blonde+dewy", "Woman Blonde Dewy", "Beauty", "Studio"],
  ["beauty-studio-woman+curly+serum", "Woman Curly Serum", "Beauty", "Studio"],
  ["beauty-studio-woman+freckled+glasses", "Woman Freckled Glasses", "Beauty", "Studio"],
  ["beauty-studio-woman+curly+orchid", "Woman Curly Orchid", "Beauty", "Studio"],
  ["beauty-studio-woman+curly+blue", "Woman Curly Blue", "Beauty", "Studio"],
  ["beauty-studio-woman+blonde+blue", "Woman Blonde Blue", "Beauty", "Studio"],
  ["beauty-studio-woman+blonde+closeup", "Woman Blonde Closeup", "Beauty", "Studio"],
  ["beauty-studio-woman+rainbow+makeup", "Woman Rainbow Makeup", "Beauty", "Studio"],
  ["beauty-studio-woman+blonde+glam", "Woman Blonde Glam", "Beauty", "Studio"],
  ["beauty-studio-woman+pink+fur", "Woman Pink Fur", "Beauty", "Studio"],
  ["beauty-studio-woman+redhead+purple", "Woman Redhead Purple", "Beauty", "Studio"],
  ["beauty-studio-woman+dark+purple", "Woman Dark Purple", "Beauty", "Studio"],
  ["beauty-studio-man+blonde+vest", "Man Blonde Vest", "Beauty", "Studio"],
  ["beauty-studio-man+curly+chains", "Man Curly Chains", "Beauty", "Studio"],
  ["beauty-studio-man+bucket+colorful", "Man Bucket Colorful", "Beauty", "Studio"],
  ["beauty-studio-man+auburn+natural", "Man Auburn Natural", "Beauty", "Studio"],
  ["beauty-studio-man+buzzcut+amber", "Man Buzzcut Amber", "Beauty", "Studio"],
  ["beauty-studio-man+wavy+white", "Man Wavy White", "Beauty", "Studio"],
  ["beauty-studio-man+dark+brown", "Man Dark Brown", "Beauty", "Studio"],
  // Beauty - Dressing Room
  ["beauty-dressingroom-woman+gold+rainbow", "Woman Gold Rainbow", "Beauty", "Dressing Room"],
  ["beauty-dressingroom-woman+redhead+luxury", "Woman Redhead Luxury", "Beauty", "Dressing Room"],
  ["beauty-dressingroom-woman+curly+warm", "Woman Curly Warm", "Beauty", "Dressing Room"],
  ["beauty-dressingroom-woman+marble+cream", "Woman Marble Cream", "Beauty", "Dressing Room"],
  ["beauty-dressingroom-woman+auburn+pink", "Woman Auburn Pink", "Beauty", "Dressing Room"],
  ["beauty-dressingroom-woman+ginger+marble", "Woman Ginger Marble", "Beauty", "Dressing Room"],
  ["beauty-dressingroom-man+taupe+gold", "Man Taupe Gold", "Beauty", "Dressing Room"],
  ["beauty-dressingroom-man+beige+grey", "Man Beige Grey", "Beauty", "Dressing Room"],
  ["beauty-dressingroom-man+black+gold", "Man Black Gold", "Beauty", "Dressing Room"],
  ["beauty-dressingroom-man+blonde+cream", "Man Blonde Cream", "Beauty", "Dressing Room"],
  // Beauty - Car
  ["beauty-car-woman+denim+sunroof", "Woman Denim Sunroof", "Beauty", "Car"],
  ["beauty-car-woman+black+luxury", "Woman Black Luxury", "Beauty", "Car"],
  ["beauty-car-woman+leather+night", "Woman Leather Night", "Beauty", "Car"],
  ["beauty-car-woman+blonde+night", "Woman Blonde Night", "Beauty", "Car"],
  ["beauty-car-woman+cognac+skyline", "Woman Cognac Skyline", "Beauty", "Car"],
  ["beauty-car-man+dark+bokeh", "Man Dark Bokeh", "Beauty", "Car"],
  ["beauty-car-man+beige+night", "Man Beige Night", "Beauty", "Car"],
  ["beauty-car-man+silver+jacket", "Man Silver Jacket", "Beauty", "Car"],
  ["beauty-car-man+navy+elegant", "Man Navy Elegant", "Beauty", "Car"],
  // Beauty - Bedroom
  ["beauty-bedroom-woman+beige+cozy", "Woman Beige Cozy", "Beauty", "Bedroom"],
  ["beauty-bedroom-woman+blonde+neutral", "Woman Blonde Neutral", "Beauty", "Bedroom"],
  ["beauty-bedroom-woman+warm+lamp", "Woman Warm Lamp", "Beauty", "Bedroom"],
  ["beauty-bedroom-woman+white+glam", "Woman White Glam", "Beauty", "Bedroom"],
  ["beauty-bedroom-woman+pink+cozy", "Woman Pink Cozy", "Beauty", "Bedroom"],
  ["beauty-bedroom-man+green+couch", "Man Green Couch", "Beauty", "Bedroom"],
  ["beauty-bedroom-woman+white+modern", "Woman White Modern", "Beauty", "Bedroom"],
  ["beauty-bedroom-man+beige+minimal", "Man Beige Minimal", "Beauty", "Bedroom"],
  // Beauty - Bathroom
  ["beauty-bathroom-woman+white+orchid", "Woman White Orchid", "Beauty", "Bathroom"],
  ["beauty-bathroom-woman+marble+vanity", "Woman Marble Vanity", "Beauty", "Bathroom"],
  ["beauty-bathroom-woman+teal+tiles", "Woman Teal Tiles", "Beauty", "Bathroom"],
  ["beauty-bathroom-woman+beige+bathtub", "Woman Beige Bathtub", "Beauty", "Bathroom"],
  ["beauty-bathroom-woman+warm+shelves", "Woman Warm Shelves", "Beauty", "Bathroom"],
  ["beauty-bathroom-man+blue+tiles", "Man Blue Tiles", "Beauty", "Bathroom"],
  ["beauty-bathroom-man+teal+pointing", "Man Teal Pointing", "Beauty", "Bathroom"],
  ["beauty-bathroom-man+navy+selfie", "Man Navy Selfie", "Beauty", "Bathroom"],
  ["beauty-bathroom-man+teal+modern", "Man Teal Modern", "Beauty", "Bathroom"],
  ["beauty-bathroom-man+gold+accents", "Man Gold Accents", "Beauty", "Bathroom"],
];

export const actors: Actor[] = raw.map(([value, label, industry, scene]) => ({
  value,
  label,
  industry,
  scene,
}));

export const industries = [...new Set(actors.map((a) => a.industry))];

export function getScenes(industry: string): string[] {
  return [...new Set(actors.filter((a) => a.industry === industry).map((a) => a.scene))];
}

export function getActors(industry: string, scene: string): Actor[] {
  return actors.filter((a) => a.industry === industry && a.scene === scene);
}

export function getVideoPreview(actorValue: string): string {
  const slug = actorValue.replace(/\+/g, "-").replace(/\s/g, "-");
  return `https://cdn.wiro.ai/uploads/sampleinputs/${slug}.mp4`;
}
